
// 영화 리스트 
export const LOAD_MOVIES_REQUEST="LOAD_MOVIES_REQUEST";
export const LOAD_MOVIES_SUCCESS="LOAD_MOVIES_SUCCESS";
export const LOAD_MOVIES_FAIL="LOAD_MOVIES_FAIL";

// 영화 1개 로딩
export const LOAD_SINGLE_MOVIE_REQUEST="LOAD_SINGLE_MOVIE_REQUEST";
export const LOAD_SINGLE_MOVIE_SUCCESS="LOAD_SINGLE_MOVIE_SUCCESS";
export const LOAD_SINGLE_MOVIE_FAIL="LOAD_SINGLE_MOVIE_FAIL";

// 연관검색어
export const LOAD_RELATED_SEARCH_REQUEST="LOAD_RELATED_SEARCH";
export const LOAD_RELATED_SEARCH_SUCCESS="LOAD_RELATED_SEARCH_SUCCESS";
export const LOAD_RELATED_SEARCH_FAIL="LOAD_RELATED_SEARCH_FAIL";
