export const LOAD_MOVIES_REQUEST="LOAD_MOVIES_REQUEST";
export const LOAD_MOVIES_SUCCESS="LOAD_MOVIES_SUCCESS";
export const LOAD_MOVIES_FAIL="LOAD_MOVIES_FAIL";

export const LOAD_SINGLE_MOVIE_REQUEST="LOAD_SINGLE_MOVIE_REQUEST";
export const LOAD_SINGLE_MOVIE_SUCCESS="LOAD_SINGLE_MOVIE_SUCCESS";
export const LOAD_SINGLE_MOVIE_FAIL="LOAD_SINGLE_MOVIE_FAIL";
