
// loadMyReviews
export const LOAD_MY_REVIEWS_REQUEST="LOAD_MY_REVIEWS_REQUEST";
export const LOAD_MY_REVIEWS_SUCCESS="LOAD_MY_REVIEWS_SUCCESS";
export const LOAD_MY_REVIEWS_FAIL="LOAD_MY_REVIEWS_FAIL";

// add My reviews
export const ADD_MY_REVIEW_REQUEST="ADD_MY_REVIEW_REQUEST";
export const ADD_MY_REVIEW_SUCCESS="ADD_MY_REVIEW_SUCCESS";
export const ADD_MY_REVIEW_FAIL="ADD_MY_REVIEW_FAIL";

// remove my Review
export const REMOVE_MY_REVIEW_REQUEST="REMOVE_MY_REVIEW_REQUEST";
export const REMOVE_MY_REVIEW_SUCCESS="REMOVE_MY_REVIEW_SUCCESS";
export const REMOVE_MY_REVIEW_FAIL="REMOVE_MY_REVIEW_FAIL";

//update my Review
export const UPDATE_MY_REVIEW_REQUEST="UPDATE_MY_REVIEW_REQUEST";
export const UPDATE_MY_REVIEW_SUCCESS="UPDATE_MY_REVIEW_SUCCESS";
export const UPDATE_MY_REVIEW_FAIL="UPDATE_MY_REVIEW_FAIL";

// save single Review
export const SAVE_SINGLE_REVIEW="SAVE_SINGLE_REVIEW"