// login actions 
export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL";

// logout actions
export const LOGOUT_REQUEST="LOGOUT_REQUEST";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_FAIL="LOGOUT_FAIL";

// signup actions 
export const SIGNUP_REQUEST="SIGNUP_REQUEST";
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS"
export const SIGNUP_FAIL="SIGNUP_FAIL";


// loadMyInfo
export const LOAD_MY_INFO_REQUEST="LOAD_MY_INFO_REQUEST";
export const LOAD_MY_INFO_SUCCESS="LOAD_MY_INFO_SUCCESS";
export const LOAD_MY_INFO_FAIL="LOAD_MY_INFO_FAIL";


// update Nickname
export const UPDATE_NICKNAME_REQUEST="UPDATE_NICKNAME_REQUEST";
export const UPDATE_NICKNAME_SUCCESS="UPDATE_NICKNAME_SUCCESS";
export const UPDATE_NICKNAME_FAIL="UPDATE_NICKNAME_FAIL";


// update profilePic
export const UPDATE_PROFILE_PIC_REQUEST="UPDATE_PROFILE_PIC_REQUEST";
export const UPDATE_PROFILE_PIC_SUCCESS="UPDATE_PROFILE_PIC_SUCCESS";
export const UPDATE_PROFILE_PIC_FAIL="UPDATE_PROFILE_PIC_FAIL";


// 인생영화 등록하기
export const ADD_FAVORITE_MOVIE_REQUEST="ADD_FAVORITE_MOVIE_REQUEST";
export const ADD_FAVORITE_MOVIE_SUCCESS="ADD_FAVORITE_MOVIE_SUCCESS";
export const ADD_FAVORITE_MOVIE_FAIL="ADD_FAVORITE_MOVIE_FAIL";

// 인생영화 로딩
export const LOAD_FAVORITE_MOVIE_REQUEST="LOAD_FAVORITE_MOVIE_REQUEST";
export const LOAD_FAVORITE_MOVIE_SUCCESS="LOAD_FAVORITE_MOVIE_SUCCESS";
export const LOAD_FAVORITE_MOVIE_FAIL="LOAD_FAVORITE_MOVIE_FAIL";